defaults:
  - base
  - _self_

traj_name: "PegIns_EeDeltaPose_State_Demo200"
num_traj: 20
num_procs: 10
obs_mode: "rgb+depth+state_dict"

motion_planning_args:
  env_id: "PegInsertionSide-v2"
  env_kwargs:
    clearance: 0.005
    robot_uids: "panda"
  solve_kwargs:
    pre_insert_aug: 0
    start_after_grasp: false
