defaults:
  - base
  - _self_

traj_name: "PegIns_Odpc_DemoVal8k"
num_traj: 100
num_procs: 20

motion_planning_args:
  env_id: "PegInsertionSide-v2"
  env_kwargs:
    clearance: 0.005
    robot_uids: "panda"
  solve_kwargs:
    pre_insert_aug: 0
    start_after_grasp: true
