env_id: "PegInsertionSide-v2"
obs_mode: "rgb+depth"
control_mode: "pd_ee_delta_pose"
num_traj: 20
only_count_success: true
traj_name: "PegIns_EeDeltaPose_HandCam_Demo20"
num_procs: 4
shader: "default"
clip: false
seed: 0

motion_planning_args:
  env_id: ${env_id}
  env_kwargs:
    clearance: 0.005
    robot_uids: "panda_peg_insertion"
    obs_mode: null
    control_mode: pd_joint_pos
    render_mode: "rgb_array"
    sim_backend: "auto"
    sensor_configs:
      shader_pack: ${shader}
    human_render_camera_configs:
      shader_pack: ${shader}
    viewer_camera_configs:
      shader_pack: ${shader}
  num_traj: ${num_traj}
  only_count_success: ${only_count_success}
  reward_mode: null
  vis: false
  save_video: false
  traj_name: ${traj_name}
  num_procs: ${num_procs}
  solve_kwargs:
    pre_insert_aug: 0
    start_after_grasp: false
  seed: ${seed}
