defaults:
  - base
  - _self_

traj_name: "PegIns_EeDeltaPose_HandCam_HoleSize5_DemoVal8k"
num_traj: 8200
num_procs: 20

motion_planning_args:
  env_id: "PegInsertionSide-v2"
  env_kwargs:
    clearance: 0.005
    robot_uids: "panda_peg_insertion"
  solve_kwargs:
    pre_insert_aug: 0
    start_after_grasp: false
