defaults:
  - base
  - _self_

traj_name: "StackCuboid_EeDeltaPose_Size20_DemoVal4k"
num_traj: 420
num_procs: 20
shader: "default"

motion_planning_args:
  env_id: "StackCuboid-v1"
  env_kwargs:
    cuboid_half_size: 0.020
    robot_uids: "panda_wristcam"
    sensor_configs:
      hand_camera:
        width: 256
        height: 256
  solve_kwargs:
    start_after_grasp: false
