traj_name: "PegIns_EeDeltaPose_HandCam_HoleSize5_DiffusionLossFinder_Dagger2k"
obs_mode: "rgbd"
control_mode: "pd_ee_delta_pose"
num_procs: 10
jpg_quality: 90
seed: 0
save_dir: demos

motion_planning_args:
  analysis_dir: runs/rollout_analysis/PegIns_DiffusionLossFinder_Rollout2k_20250817_223736
  output_dir: ${save_dir}
  traj_name: ${traj_name}
  num_procs: ${num_procs}
  vis: False
  save_video: False
  only_count_success: True
  seed: ${seed}
  num_trajs: 2000
