exp_name: "odpc"
seed: 42
obs_horizon: 1
act_horizon: 8
pred_horizon: 16

torch_deterministic: true
track: true
wandb_project_name: "ManiSkill"
wandb_entity: null

obs_mode: state_dict+rgb+depth+segmentation
control_mode: pd_ee_pose

num_envs: 20

save_dir: runs/${exp_name}

trainer:
  total_iters: 400010
  batch_size: 256
  save_freq: 40000
  eval_freq: 40000
  log_freq: 1000
  num_dataload_workers: 8

obs_processor_configs:
  - _target_: odpc.data.obs_processors.ClampDepthProcessor
    depth_threshold: 3000
    clamp_to_zero: true
  - _target_: odpc.data.obs_processors.SimpleNormalizeProcessor
  - _target_: odpc.data.obs_processors.TcpCropProcessor
    crop_size: [128, 128]
    padding_value: 0
    camera_name: base_camera
    output_postfix: _crop

act_processor_configs:
  - _target_: odpc.data.act_processors.ODPCProcessor
    dc_config: 
      _target_: odpc.data.data_conversion.DataConversion
      frame: camera_first
      delta_pred: rel_to_prev
      rot_rep: axis_angle
      control_mode: ${control_mode}
      dt: 0.05
    output_key: actions

train_dataset:
  _target_: odpc.data.odpc_dataset.ODPCDataset
  data_path: demos/peg_insertion_demo.state_dict+rgb+depth+segmentation.pd_ee_pose.physx_cpu.h5
  obs_horizon: ${obs_horizon}
  pred_horizon: ${pred_horizon}
  num_traj: 1000
  clip_traj: false
  obs_processor_configs: ${obs_processor_configs}
  act_processor_configs: ${act_processor_configs}

data_conversion:
  _target_: odpc.data.data_conversion.DataConversion
  frame: camera_first
  delta_pred: rel_to_prev
  rot_rep: axis_angle
  control_mode: ${control_mode}
  dt: 0.05

model:
  _target_: odpc.models.odpc.ODPCModel
  obs_horizon: ${obs_horizon}
  pred_horizon: ${pred_horizon}
  output_dim: 6
  visual_encoder_config:
    _target_: odpc.models.vision.Resnet18Encoder
    obs_meta:
      base_camera:
        type: rgbd
        rgb: sensor_data.base_camera.rgb
        depth: sensor_data.base_camera.depth
        shape: [1, 4, 256, 256]
        output_dim: 256
      base_camera_crop:
        type: rgbd
        rgb: sensor_data.base_camera.rgb_crop
        depth: sensor_data.base_camera.depth_crop
        shape: [1, 4, 128, 128]
        output_dim: 256
  noise_pred_net_config:
    _target_: diffusion_policy.conditional_unet1d.ConditionalUnet1D
    input_dim: ${model.output_dim}
    global_cond_dim: 512
    diffusion_step_embed_dim: 64
    down_dims: [64, 128, 256]
    n_groups: 8
  noise_scheduler_config:
    _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
    num_train_timesteps: 100
    beta_schedule: "squaredcos_cap_v2"
    clip_sample: true
    prediction_type: "epsilon"


evaluator:
  _target_: odpc.evaluation.evaluate.Evaluator

  env_configs:
    ind:
      env:
        _target_: odpc.envs.factory.make_eval_envs.make_eval_envs
        env_id: PegInsertionSide-v2
        num_envs: ${num_envs}
        sim_backend: cuda
        env_kwargs:
          obs_mode: ${obs_mode}
          control_mode: ${control_mode}
          reward_mode: sparse
          render_mode: rgb_array
          human_render_camera_configs:
            shader_pack: default
          sensor_configs:
            shader_pack: default
          robot_uids: panda
          camera_mode: fixed
          max_episode_steps: 300
        other_kwargs:
          obs_horizon: ${obs_horizon}
        video_dir: ${save_dir}/videos/ind_render
      agent:
        _target_: odpc.models.agent.ODPCAgent
        num_envs: ${num_envs}
        act_horizon: ${act_horizon}
        pred_horizon: ${pred_horizon}
        control_mode: ${control_mode}
        robot_uid: panda
        video_dir: ${save_dir}/videos/ind_pred
        obs_processor_configs: ${obs_processor_configs}
    # ood: todo

  dataset_configs:
    ind:
      _target_: odpc.data.odpc_dataset.ODPCDataset
      data_path: demos/peg_insertion_demo.state_dict+rgb+depth+segmentation.pd_ee_pose.physx_cpu.h5
      obs_horizon: ${obs_horizon}
      pred_horizon: ${pred_horizon}
      num_traj: 100
      clip_traj: false
      obs_processor_configs: ${obs_processor_configs}
      act_processor_configs: ${act_processor_configs}
    # ood: todo



optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-4
  betas: [0.95, 0.999]
  weight_decay: 1e-6

lr_scheduler:
  _target_: diffusers.optimization.get_scheduler
  name: cosine
  num_warmup_steps: 500
  num_training_steps: ${trainer.total_iters}

